config/routes.rb
Rails.application.routes.draw do
  
  get "/photos/new", {:controller => "photos", :action => "new",    :as => "new_photo"}
  post "/photos",    {:controller => "photos", :action => "create", :as => "photos"}
  
  
  get "/photos/:id", {:controller => "photos", :action => "show", :as => "photo"}
  get "/photos",     {:controller => "photos", :action => "index"}
  
  
  get "/photos/:id/edit", {:controller => "photos", :action => "edit", :as => "edit_photo"}
  patch "/photos/:id",   {:controller => "photos", :action => "update"}
  
  
  delete "photos/:id",  {:controller => "photos", :action => "destroy"}
  
  
  
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
    validates :caption, presence: true
    validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #create
  def new
    @var=Photo.new   #create the instance variable to display an error in the show page
    render "new"
  end 
  def create
    @var=Photo.new
    @var.caption=params["caption"]
    @var.photo=params["photo"]
    if @var.save
      redirect_to photo_url(@var.id)#redirect_to "/photos/#{@var.id}"
    else
       render "new"
    end   
  end 
  
  
  #Read
  def show
        @var=Photo.find_by(:id => params[:id])
        if @var.present?
            render "show"
        else
            redirect_to photos_url, :notice => "The record doesn't exit"
        end
  end
  
  def index
    @var=Photo.all
    render "index"
  end
  
  #Update
  def edit
    @var=Photo.find(params[:id])
    render "edit"
  end
  
  def update
    @var=Photo.find(params[:id])
    @var.caption = params["caption"]
    @var.photo   = params["photo"]
    @var.save
    redirect_to photo_url(@var.id)
  end
  
  
  #Destroy
  def destroy
    @var=Photo.find(params[:id])
    @var.destroy
    redirect_to photos_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/photos/destroy.html.erb
<h1>The record has been deleted</h1>

app/views/photos/edit.html.erb
<h1>Edit Page</h1>

<%= form_tag(photo_path(@var.id), :method => :patch) do %> 
    
    <label for="caption"> Caption
        <input type="text"  id="caption"    name="caption"  value="<%= @var.caption %>">
    </label>
    <label for="photo"> URL
        <input  type="text" id="photo"      name="photo"     value="<%= @var.photo %>">
    </label>
    <input type="submit">
    
<% end %>

app/views/photos/index.html.erb
<h1>Index Page</h1>


<% @var.each do |pointer| %> 
        
    <%= link_to photo_path(pointer.id) do %>
         <p> Caption: <%= pointer.caption %> </p>
         <img src="<%= pointer.photo %>">
       
  <% end %>
    
<% end %>

app/views/photos/new.html.erb
<h1>New Record </h1>
<% if @var.errors.present? %>
    <p>The following error prevented your photo for being saved</p>
    <ul>
      <% @var.errors.full_messages.each do |message| %>
       <li> <%= message %></li>
       <% end %>
   </ul>
<% end %>


<%= form_tag(photos_path) do %> 
    
    <label for="caption"> Caption
        <input type="text"  id="caption"    name="caption"  value=<%=@var.caption%> >
    </label>
    <label for="photo"> URL
        <input  type="text" id="photo"      name="photo"   value=<%=@var.photo%> >
    </label>
    <input type="submit">
    
<% end %>

<!--

<form method="post" action="/photos">
    
    <input name="authenticity_token" value="<%#=form_authenticity_token %>" type="hidden">
    
    <label for="caption">
        Caption: <input type="text" id="caption" name="caption">
    </label>
    <label for="photo">
        Photo URL: <input type="text" id="photo" name="photo">
    </label>
    
    <input type="submit">
    
</form> -->

app/views/photos/show.html.erb
<h1>Display Model Records</h1>

<img src="<%= @var.photo %>">
<p>Caption <%= @var.caption %> </p>


   <!-- <a href="/photos/<%= @var.id %>/edit">Edit</a> -->
    <%= link_to "Edit", edit_photo_path(@var.id) %>
    
   <!-- <a href="/photos/<%= @var.id %>" data-confirm="Are you sure?" data-method="delete">Delete</a> -->
    <%= link_to "Delete", photo_path(@var.id), {:method => :delete, :data => {:confirm => "Are you sure"}}%>